# Default values for task-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 904555500270.dkr.ecr.eu-west-1.amazonaws.com/my-first-helm
  tag: "1.0"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

api:
  prefix: "/api/v1"
  
database:
  path: "/data/tasks.db"
  password: "cGFzc3dvcmQxMjM="  # Should be overridden in production

persistence:
  enabled: true
  storageClass: "local-storage"
  accessMode: ReadWriteOnce
  size: 1Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
