# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tasks-api.fullname" . }}-config
  labels:
    {{- include "tasks-api.labels" . | nindent 4 }}
data:
  API_PREFIX: {{ .Values.api.prefix }}
  DB_PATH: {{ .Values.database.path }}

---
# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tasks-api.fullname" . }}-secret
  labels:
    {{- include "tasks-api.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.database.password | b64enc }}

---
# templates/pvc.yaml
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tasks-api.fullname" . }}-pvc
  labels:
    {{- include "tasks-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}

---
# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tasks-api.fullname" . }}
  labels:
    {{- include "tasks-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tasks-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tasks-api.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "tasks-api.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: API_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tasks-api.fullname" . }}-config
                  key: API_PREFIX
            - name: DB_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "tasks-api.fullname" . }}-config
                  key: DB_PATH
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "tasks-api.fullname" . }}-secret
                  key: DB_PASSWORD
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "tasks-api.fullname" . }}-pvc

---
# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tasks-api.fullname" . }}
  labels:
    {{- include "tasks-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "tasks-api.selectorLabels" . | nindent 4 }}

---
# templates/_helpers.tpl
{{/*
Expand the name of the chart.
*/}}
{{- define "tasks-api.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "tasks-api.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "tasks-api.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "tasks-api.labels" -}}
helm.sh/chart: {{ include "tasks-api.chart" . }}
{{ include "tasks-api.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "tasks-api.selectorLabels" -}}
app.kubernetes.io/name: {{ include "tasks-api.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "tasks-api.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "tasks-api.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}
